/**
 * IC catalog used by the gate library and IC node renderer.
 * Each definition includes visual metadata and explicit pin definitions.
 */

const bits = (prefix, count, labelPrefix = prefix.toUpperCase()) =>
  Array.from({ length: count }, (_, i) => ({ id: `${prefix}${i}`, label: `${labelPrefix}${i}` }));

const decoderOutputs = (count) =>
  Array.from({ length: count }, (_, i) => ({ id: `y${i}`, label: `Y${i}` }));

export const IC_CONFIGS = {
  HALF_ADDER: {
    label: 'Half Adder',
    short: 'HA',
    desc: 'A,B -> S,C',
    color: '#06B6D4',
    bg: '#0A2030',
    border: '#0E4060',
    expandable: true,
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }],
    outputs: [{ id: 'sum', label: 'S' }, { id: 'carry', label: 'C' }],
  },
  FULL_ADDER: {
    label: 'Full Adder',
    short: 'FA',
    desc: 'A,B,Cin -> S,Cout',
    color: '#8B5CF6',
    bg: '#1A0A30',
    border: '#3A1060',
    expandable: true,
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }, { id: 'cin', label: 'Cin' }],
    outputs: [{ id: 'sum', label: 'S' }, { id: 'carry', label: 'Cout' }],
  },
  RCA_4: {
    label: 'Ripple Carry Adder (4-bit)',
    short: 'RCA4',
    desc: 'A[3:0],B[3:0],Cin',
    color: '#14B8A6',
    bg: '#05231F',
    border: '#0A4A42',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'cin', label: 'Cin' }],
    outputs: [...bits('s', 4, 'S'), { id: 'cout', label: 'Cout' }],
  },
  CLA_4: {
    label: 'Carry Lookahead Adder (4-bit)',
    short: 'CLA4',
    desc: 'Fast carry adder',
    color: '#0EA5E9',
    bg: '#071C2A',
    border: '#134869',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'cin', label: 'Cin' }],
    outputs: [...bits('s', 4, 'S'), { id: 'cout', label: 'Cout' }],
  },
  CSA_4: {
    label: 'Carry Select Adder (4-bit)',
    short: 'CSA4',
    desc: 'Dual carry path',
    color: '#06B6D4',
    bg: '#04222A',
    border: '#0E5563',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'cin', label: 'Cin' }],
    outputs: [...bits('s', 4, 'S'), { id: 'cout', label: 'Cout' }],
  },
  KSA_4: {
    label: 'Carry Skip Adder (4-bit)',
    short: 'KSA4',
    desc: 'Skip carry blocks',
    color: '#22C55E',
    bg: '#052312',
    border: '#1C5A34',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'cin', label: 'Cin' }],
    outputs: [...bits('s', 4, 'S'), { id: 'cout', label: 'Cout' }],
  },
  BINARY_ADD_SUB_4: {
    label: 'Binary Adder/Subtractor (4-bit)',
    short: 'ADD/SUB',
    desc: 'Mode=0 add, 1 subtract',
    color: '#84CC16',
    bg: '#1A2206',
    border: '#4E6418',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'mode', label: 'M' }],
    outputs: [...bits('s', 4, 'R'), { id: 'cout', label: 'C/B' }],
  },

  MUX_2_1: {
    label: '2-to-1 MUX',
    short: 'MUX2',
    desc: 'd0,d1,s0 -> y',
    color: '#F59E0B',
    bg: '#201800',
    border: '#503800',
    expandable: true,
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }, { id: 'sel', label: 'S' }],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  MUX_4_1: {
    label: '4-to-1 MUX',
    short: 'MUX4',
    desc: '4 data, 2 select',
    color: '#FB923C',
    bg: '#2A1706',
    border: '#6A3E12',
    inputs: [...bits('d', 4, 'D'), ...bits('s', 2, 'S')],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  MUX_8_1: {
    label: '8-to-1 MUX',
    short: 'MUX8',
    desc: '8 data, 3 select',
    color: '#F97316',
    bg: '#2A1305',
    border: '#7A330D',
    inputs: [...bits('d', 8, 'D'), ...bits('s', 3, 'S')],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  MUX_16_1: {
    label: '16-to-1 MUX',
    short: 'MUX16',
    desc: '16 data, 4 select',
    color: '#EA580C',
    bg: '#2A1104',
    border: '#7A2F0A',
    inputs: [...bits('d', 16, 'D'), ...bits('s', 4, 'S')],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  MUX_TREE_8: {
    label: 'Multiplexer Tree (8-to-1)',
    short: 'TREE',
    desc: 'Hierarchical mux tree',
    color: '#F59E0B',
    bg: '#261B08',
    border: '#6A4A12',
    inputs: [...bits('d', 8, 'D'), ...bits('s', 3, 'S')],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  PRIORITY_MUX_ENCODER_8: {
    label: 'Priority Encoder (MUX-based)',
    short: 'PME8',
    desc: 'Highest active input',
    color: '#D97706',
    bg: '#271A08',
    border: '#70420F',
    inputs: bits('i', 8, 'I'),
    outputs: [{ id: 'b0', label: 'B0' }, { id: 'b1', label: 'B1' }, { id: 'b2', label: 'B2' }, { id: 'valid', label: 'V' }],
  },

  SR_FLIPFLOP: {
    label: 'SR Flip-Flop',
    short: 'SR',
    desc: 'S,R,Clk -> Q,Qbar',
    color: '#EC4899',
    bg: '#230914',
    border: '#5A183A',
    inputs: [{ id: 's', label: 'S' }, { id: 'r', label: 'R' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  D_FLIPFLOP: {
    label: 'D Flip-Flop',
    short: 'DFF',
    desc: 'D,Clk -> Q,Qbar',
    color: '#EC4899',
    bg: '#200A18',
    border: '#501030',
    expandable: true,
    inputs: [{ id: 'd', label: 'D' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  JK_FLIPFLOP: {
    label: 'JK Flip-Flop',
    short: 'JK',
    desc: 'J,K,Clk -> Q,Qbar',
    color: '#F472B6',
    bg: '#250A18',
    border: '#662040',
    inputs: [{ id: 'j', label: 'J' }, { id: 'k', label: 'K' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  T_FLIPFLOP: {
    label: 'T Flip-Flop',
    short: 'TFF',
    desc: 'T,Clk -> Q,Qbar',
    color: '#DB2777',
    bg: '#260913',
    border: '#6B1E40',
    inputs: [{ id: 't', label: 'T' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  MASTER_SLAVE_FF: {
    label: 'Master-Slave Flip-Flop',
    short: 'MSFF',
    desc: 'Edge-like behavior',
    color: '#BE185D',
    bg: '#29080F',
    border: '#741C46',
    inputs: [{ id: 'd', label: 'D' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  EDGE_TRIGGERED_FF: {
    label: 'Edge-Triggered Flip-Flop',
    short: 'ETFF',
    desc: 'Rising edge latch',
    color: '#9D174D',
    bg: '#2A0A12',
    border: '#6A1D3C',
    inputs: [{ id: 'd', label: 'D' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },
  LEVEL_TRIGGERED_FF: {
    label: 'Level-Triggered Flip-Flop',
    short: 'LTFF',
    desc: 'Transparent when Clk=1',
    color: '#831843',
    bg: '#2A0912',
    border: '#651F3E',
    inputs: [{ id: 'd', label: 'D' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }, { id: 'qbar', label: 'Qbar' }],
  },

  SISO_SHIFT_4: {
    label: 'Shift Register SISO (4-bit)',
    short: 'SISO4',
    desc: 'Serial in, serial out',
    color: '#0EA5E9',
    bg: '#071F2A',
    border: '#14506A',
    inputs: [{ id: 'sin', label: 'Sin' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'sout', label: 'Sout' }],
  },
  SIPO_SHIFT_4: {
    label: 'Shift Register SIPO (4-bit)',
    short: 'SIPO4',
    desc: 'Serial in, parallel out',
    color: '#0284C7',
    bg: '#061E2A',
    border: '#0B4A68',
    inputs: [{ id: 'sin', label: 'Sin' }, { id: 'clk', label: 'Clk' }],
    outputs: [...bits('q', 4, 'Q')],
  },
  PISO_SHIFT_4: {
    label: 'Shift Register PISO (4-bit)',
    short: 'PISO4',
    desc: 'Parallel in, serial out',
    color: '#0369A1',
    bg: '#081C28',
    border: '#114461',
    inputs: [...bits('p', 4, 'P'), { id: 'load', label: 'Ld' }, { id: 'sin', label: 'Sin' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'sout', label: 'Sout' }, ...bits('q', 4, 'Q')],
  },
  PIPO_SHIFT_4: {
    label: 'Shift Register PIPO (4-bit)',
    short: 'PIPO4',
    desc: 'Parallel in, parallel out',
    color: '#075985',
    bg: '#071A24',
    border: '#0F3E59',
    inputs: [...bits('p', 4, 'P'), { id: 'clk', label: 'Clk' }],
    outputs: [...bits('q', 4, 'Q')],
  },
  UNIVERSAL_SHIFT_4: {
    label: 'Universal Shift Register (4-bit)',
    short: 'USR4',
    desc: 'Hold, shift, load',
    color: '#0891B2',
    bg: '#062029',
    border: '#0D4F60',
    inputs: [
      ...bits('p', 4, 'P'),
      { id: 'sinl', label: 'SinL' },
      { id: 'sinr', label: 'SinR' },
      { id: 's0', label: 'S0' },
      { id: 's1', label: 'S1' },
      { id: 'clk', label: 'Clk' },
    ],
    outputs: [...bits('q', 4, 'Q')],
  },
  RIPPLE_COUNTER_4: {
    label: 'Ripple Counter (4-bit)',
    short: 'RCNT4',
    desc: 'Async counter',
    color: '#6366F1',
    bg: '#10122D',
    border: '#353A7A',
    inputs: [{ id: 'clk', label: 'Clk' }, { id: 'rst', label: 'Rst' }, { id: 'en', label: 'En' }],
    outputs: [...bits('q', 4, 'Q')],
  },
  SYNC_COUNTER_4: {
    label: 'Synchronous Counter (4-bit)',
    short: 'SCNT4',
    desc: 'Sync counter',
    color: '#4F46E5',
    bg: '#0F112B',
    border: '#302E78',
    inputs: [{ id: 'clk', label: 'Clk' }, { id: 'rst', label: 'Rst' }, { id: 'en', label: 'En' }],
    outputs: [...bits('q', 4, 'Q')],
  },
  UP_DOWN_COUNTER_4: {
    label: 'Up/Down Counter (4-bit)',
    short: 'UDCNT4',
    desc: 'Dir controls count',
    color: '#4338CA',
    bg: '#0E1028',
    border: '#2A2966',
    inputs: [{ id: 'clk', label: 'Clk' }, { id: 'rst', label: 'Rst' }, { id: 'en', label: 'En' }, { id: 'dir', label: 'Dir' }],
    outputs: [...bits('q', 4, 'Q')],
  },

  DECODER_2_4: {
    label: 'Decoder 2-to-4',
    short: 'DEC24',
    desc: 'Binary to one-hot',
    color: '#A855F7',
    bg: '#1D0F2C',
    border: '#5A2D84',
    inputs: bits('a', 2, 'A'),
    outputs: decoderOutputs(4),
  },
  DECODER_3_8: {
    label: 'Decoder 3-to-8',
    short: 'DEC38',
    desc: 'Binary to one-hot',
    color: '#9333EA',
    bg: '#1C0E2A',
    border: '#582A7A',
    inputs: bits('a', 3, 'A'),
    outputs: decoderOutputs(8),
  },
  DECODER_4_16: {
    label: 'Decoder 4-to-16',
    short: 'DEC416',
    desc: 'Binary to one-hot',
    color: '#7E22CE',
    bg: '#1A0D28',
    border: '#4E2574',
    inputs: bits('a', 4, 'A'),
    outputs: decoderOutputs(16),
  },
  PRIORITY_ENCODER_8_3: {
    label: 'Priority Encoder (8-to-3)',
    short: 'PE83',
    desc: 'Highest-priority input',
    color: '#C026D3',
    bg: '#220D2A',
    border: '#6A2878',
    inputs: bits('i', 8, 'I'),
    outputs: [{ id: 'b0', label: 'B0' }, { id: 'b1', label: 'B1' }, { id: 'b2', label: 'B2' }, { id: 'valid', label: 'V' }],
  },
  OCTAL_BINARY_ENCODER_8_3: {
    label: 'Octal/Binary Encoder (8-to-3)',
    short: 'ENC83',
    desc: 'Binary encode active input',
    color: '#D946EF',
    bg: '#250D2C',
    border: '#7A2E82',
    inputs: bits('i', 8, 'I'),
    outputs: [{ id: 'b0', label: 'B0' }, { id: 'b1', label: 'B1' }, { id: 'b2', label: 'B2' }, { id: 'valid', label: 'V' }],
  },

  COMPARATOR_1BIT: {
    label: 'Comparator 1-bit',
    short: 'CMP1',
    desc: 'A vs B',
    color: '#10B981',
    bg: '#0A2218',
    border: '#1F5B45',
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }],
    outputs: [{ id: 'eq', label: 'EQ' }, { id: 'gt', label: 'GT' }, { id: 'lt', label: 'LT' }],
  },
  COMPARATOR_4BIT: {
    label: 'Comparator n-bit (4-bit)',
    short: 'CMP4',
    desc: 'A[3:0] vs B[3:0]',
    color: '#059669',
    bg: '#0A2018',
    border: '#1A5A42',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B')],
    outputs: [{ id: 'eq', label: 'EQ' }, { id: 'gt', label: 'GT' }, { id: 'lt', label: 'LT' }],
  },

  DEMUX_1_4: {
    label: 'Demultiplexer (1-to-4)',
    short: 'DEMUX',
    desc: 'D routed by select',
    color: '#14B8A6',
    bg: '#072320',
    border: '#1A5D56',
    inputs: [{ id: 'd', label: 'D' }, { id: 's0', label: 'S0' }, { id: 's1', label: 'S1' }],
    outputs: decoderOutputs(4),
  },
  MUX_BASED_ADD_SUB_4: {
    label: 'MUX-based Adder/Subtractor (4-bit)',
    short: 'MADD4',
    desc: 'Select add/sub path',
    color: '#16A34A',
    bg: '#0B2312',
    border: '#28603A',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'mode', label: 'M' }],
    outputs: [...bits('s', 4, 'R'), { id: 'cout', label: 'C/B' }],
  },
  BUFFER_IC: {
    label: 'Buffer',
    short: 'BUF',
    desc: 'Signal buffer',
    color: '#22D3EE',
    bg: '#08252B',
    border: '#1E6877',
    inputs: [{ id: 'a', label: 'A' }],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  INVERTER_IC: {
    label: 'Inverter',
    short: 'INV',
    desc: 'Logic inversion',
    color: '#38BDF8',
    bg: '#08212C',
    border: '#1B5F7C',
    inputs: [{ id: 'a', label: 'A' }],
    outputs: [{ id: 'y', label: 'Y' }],
  },
  CLOCKED_LOGIC: {
    label: 'Clocked Logic Element',
    short: 'CLK',
    desc: 'Passes input on clock',
    color: '#F43F5E',
    bg: '#280912',
    border: '#6A2138',
    inputs: [{ id: 'd', label: 'D' }, { id: 'clk', label: 'Clk' }],
    outputs: [{ id: 'q', label: 'Q' }],
  },

  ALU_4: {
    label: 'ALU (4-bit)',
    short: 'ALU4',
    desc: 'ADD,SUB,AND,OR',
    color: '#F97316',
    bg: '#2A1307',
    border: '#7A360F',
    inputs: [...bits('a', 4, 'A'), ...bits('b', 4, 'B'), { id: 'op0', label: 'Op0' }, { id: 'op1', label: 'Op1' }],
    outputs: [...bits('y', 4, 'Y'), { id: 'cout', label: 'Cout' }, { id: 'zero', label: 'Z' }, { id: 'neg', label: 'N' }],
  },
  MULTIPLIER_2: {
    label: 'Multiplier (2-bit x 2-bit)',
    short: 'MUL2',
    desc: 'A[1:0] * B[1:0]',
    color: '#FB7185',
    bg: '#2A0F15',
    border: '#7A2D3E',
    inputs: bits('a', 2, 'A').concat(bits('b', 2, 'B')),
    outputs: bits('p', 4, 'P'),
  },
  DIVIDER_2: {
    label: 'Divider (2-bit / 2-bit)',
    short: 'DIV2',
    desc: 'Quotient + remainder',
    color: '#F43F5E',
    bg: '#2A0C13',
    border: '#7A2638',
    inputs: bits('a', 2, 'A').concat(bits('b', 2, 'B')),
    outputs: [{ id: 'q0', label: 'Q0' }, { id: 'q1', label: 'Q1' }, { id: 'r0', label: 'R0' }, { id: 'r1', label: 'R1' }, { id: 'div0', label: 'Div0' }],
  },

  PARITY_GENERATOR_4: {
    label: 'Parity Generator (4-bit)',
    short: 'PGEN4',
    desc: 'Even and odd parity',
    color: '#A3E635',
    bg: '#1C2507',
    border: '#587A19',
    inputs: bits('a', 4, 'A'),
    outputs: [{ id: 'even', label: 'Even' }, { id: 'odd', label: 'Odd' }],
  },
  PARITY_CHECKER_4: {
    label: 'Parity Checker (4-bit)',
    short: 'PCHK4',
    desc: 'Checks parity bit',
    color: '#84CC16',
    bg: '#1A2406',
    border: '#4C7315',
    inputs: [...bits('a', 4, 'A'), { id: 'p', label: 'P' }],
    outputs: [{ id: 'ok', label: 'OK' }, { id: 'err', label: 'ERR' }],
  },
  HALF_SUBTRACTOR: {
    label: 'Half Subtractor',
    short: 'HS',
    desc: 'A,B -> Diff,Borrow',
    color: '#EF4444',
    bg: '#2A0C0C',
    border: '#7A2A2A',
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }],
    outputs: [{ id: 'diff', label: 'D' }, { id: 'borrow', label: 'B' }],
  },
  FULL_SUBTRACTOR: {
    label: 'Full Subtractor',
    short: 'FS',
    desc: 'A,B,Bin -> Diff,Bout',
    color: '#DC2626',
    bg: '#2A0A0A',
    border: '#7A2020',
    inputs: [{ id: 'a', label: 'A' }, { id: 'b', label: 'B' }, { id: 'bin', label: 'Bin' }],
    outputs: [{ id: 'diff', label: 'D' }, { id: 'borrow', label: 'Bout' }],
  },
};

export const IC_CATEGORIES = [
  {
    title: 'Adders',
    items: ['HALF_ADDER', 'FULL_ADDER', 'RCA_4', 'CLA_4', 'CSA_4', 'KSA_4', 'BINARY_ADD_SUB_4'],
  },
  {
    title: 'Multiplexers',
    items: ['MUX_2_1', 'MUX_4_1', 'MUX_8_1', 'MUX_16_1', 'MUX_TREE_8', 'PRIORITY_MUX_ENCODER_8'],
  },
  {
    title: 'Flip-Flops',
    items: ['SR_FLIPFLOP', 'D_FLIPFLOP', 'JK_FLIPFLOP', 'T_FLIPFLOP', 'MASTER_SLAVE_FF', 'EDGE_TRIGGERED_FF', 'LEVEL_TRIGGERED_FF'],
  },
  {
    title: 'Registers & Counters',
    items: ['SISO_SHIFT_4', 'SIPO_SHIFT_4', 'PISO_SHIFT_4', 'PIPO_SHIFT_4', 'UNIVERSAL_SHIFT_4', 'RIPPLE_COUNTER_4', 'SYNC_COUNTER_4', 'UP_DOWN_COUNTER_4'],
  },
  {
    title: 'Decoders & Encoders',
    items: ['DECODER_2_4', 'DECODER_3_8', 'DECODER_4_16', 'PRIORITY_ENCODER_8_3', 'OCTAL_BINARY_ENCODER_8_3'],
  },
  {
    title: 'Comparators',
    items: ['COMPARATOR_1BIT', 'COMPARATOR_4BIT'],
  },
  {
    title: 'Other Logic Components',
    items: ['DEMUX_1_4', 'MUX_BASED_ADD_SUB_4', 'BUFFER_IC', 'INVERTER_IC', 'CLOCKED_LOGIC'],
  },
  {
    title: 'ALU Components',
    items: ['ALU_4', 'MULTIPLIER_2', 'DIVIDER_2'],
  },
  {
    title: 'Specialized Elements',
    items: ['PARITY_GENERATOR_4', 'PARITY_CHECKER_4', 'HALF_SUBTRACTOR', 'FULL_SUBTRACTOR'],
  },
];

export const ALL_IC_TYPES = Object.keys(IC_CONFIGS);
